// packages/react-keycon/src/App.tsx
import React, { useRef } from 'react';
import './App.css';
import { useKeycon } from './react-keycon/useKeycon';

function App() {
  const { isKeydown } = useKeycon({
    keys: ["shift"],
  });

  return (
    <div className="App">
      {isKeydown ? "keydown" : "keyup"}
    </div>
  );
}

export default App;

// packages/vue2-keycon/demo/App.vue
<template>
  <div class="App">
    {{ isKeydown ? "keydown" : "keyup" }}
  </div>
</template>
<script>
import { useKeycon } from "../src/index";

export default {
  setup() {
    const { isKeydown } = useKeycon({
      keys: ["shift"],
    });

    return {
      isKeydown,
    };
  },
};
</script>
